### ISSUE TITLE
Remove copying private information from Dockerfile

### ISSUE THREAD

**Issue by nicmr** [Altemista/altemista-billing#14]
currently we copy ./aws/credentials, that should never happen to avoid leaking private data into the image. Instead, mount a credentials file at run time and add corresponding instructions to documentation.

**Comment by cheld** [comment]
Credentials should be stored in central encrypted repository. For testing, credentials can be stored in Travis and imported as environment variable

**Comment by nicmr** [comment]
Merged with 437f5675526ab0d6b515bd04a548f00cb1538539
