### ISSUE TITLE
Research: user interaction, output data, SAP integration

### ISSUE THREAD

**Issue by nicmr** [Altemista/altemista-billing#2]
As a preliminary form of user-directed output, the program should generate CSV files per customer with their associated resource cost.

**Comment by nicmr** [comment]
go std lib:  encoding/csv

**Comment by cheld** [comment]
I think it is less error prone for a person to enter data to SAP if all data is in single file. Maybe SAP has import format? Please clarifiy the process before polishing the implementation.

**Comment by markushinz** [comment]
csv file now has format "TimePeriodStart,TimePeriodEnd,Amount" listing all costs in range (per day). Before splitting costs or further processing we'll investigate SAP's requirements

**Comment by nicmr** [comment]
Major questions:
- What information do our users need:
  - accountant that enters billing data into CSV
  - customer that wants to track what he's spent
  - Altemista team to track who is provisioning how much from us
  --> Create separate issues once requirements are clear.

- How should users receive this information? Mail? S3 bucket? Website?
- What are the requirements for eventually achieving automated integration with SAP?
- Is it sufficient if the application runs as a cron job, or does it need to be able to respond to requests?

**Comment by nicmr** [comment]
Results:
Information required by:
- Accountant that enters billing data into SAP:
  - CSV with the following col headers: ID, Project number, Project, Contact Person, Amount
  - Read from S3
  - Notified by mail
- [ further results will be added here ]

**Comment by cheld** [comment]
Step 1:
 the accountant should receive manual email. 

Step 2:
User should get email

Step 3:
Automate billing process to accountant.e.g by email

**Comment by nicmr** [comment]
The insights gained from the discussion here have all been resolved, received their own issue, or are covered by #4 .
If we ever get the permission to integrate directly with SAP, we'll create a separate issue for that.
