### ISSUE TITLE
Cronjob deployment

### ISSUE THREAD

**Issue by cheld** [Altemista/altemista-billing#26]
Please create job deployment descriptor, deploy to demo cluster and test the full process

**Comment by nicmr** [comment]
- [ ] Kubernetes cron job creation & configuration https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/
- [ ] Deploy to demo cluster
- [ ] Test end-to-end

**Comment by nicmr** [comment]
Cronjob deployment development can be tracked on [feature/cronjob](/Altemista/altemista-billing/tree/feature/cronjob)

**Comment by nicmr** [comment]
Awaiting review at #36

**Comment by nicmr** [comment]
#36 has been merged, now I'm going to try and deploy it on kubernetes

**Comment by nicmr** [comment]
Some last fixes for the cronjob spec are awaiting reivew at #43 

The deployment has been tested on K8s and works fine, only passing aws secrets remains a hassle.

**Comment by nicmr** [comment]
Merged with #43
