### ISSUE TITLE
Rename --api flag

### ISSUE THREAD

**Issue by nicmr** [Altemista/altemista-billing#37]
Christoph has suggested we rename the --api flag to something more appropriate.
His suggestion was to name it `--provider` instead, which is already a lot better imo.

The corresponding shorthand flag name would be `-p`, which I would like to avoid since it is usually associated with a port flag - in fact, we use it for the port flag of a different subcommand.
As a result, we should either not offer a shorthand flag, use a multi letter short hand flag instead (`-prv`), or come with an even better name for this flag.

I'd appreciate further suggestions.

**Comment by markushinz** [comment]
hm - provider sounds good to me. but -p has to be the port, I agree. But if it's gonna be --provider I would not offer a shorthand at all.

What about cloud(provider) ? We could do a -c then.

**Comment by nicmr** [comment]
For now, I'm going to rename it to provider, but keep the issue open.
